[workspace]
members = [
  "posts/post1-invisible-wall",
  "posts/post2-elastic-wall",
  "benchmarks",
  "posts/shared",
]

resolver = "3"

[workspace.dependencies]
colored = "3.0.0"
clap = { version = "4.5.36", features = ["derive"] }
criterion = "0.6.0"
