[package]
name = "post2-elastic-wall"
version = "0.1.0"
edition = "2024"
publish = false


license = "MIT"

[dependencies]
colored = { workspace = true }
clap = { workspace = true }
shared = { path = "../shared/" }
