name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          keep-env-derivations = true
          keep-outputs = true

    - name: Use public Cachix cache
      uses: cachix/cachix-action@v16
      with:
        name: hash-tables-without-assumptions
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Install Swam Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Run tests inside Nix shell
      run: nix develop --command just ci
